# -*- coding: utf-8 -*-
"""programa distancia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SnzLTZrY1x96USfioI3ZigiyXNV7Ikhu
"""

import urllib.parse
import requests

main_api = "https://www.mapquestapi.com/directions/v2/route?"
key = "MH8fP1eWwocnjGKANwvV5f5TJihAAort"

# Estimated Gasoline Consumption
def calculate_gasoline_consumption(distance):
    gasoline_consumption = distance * 0.05
    return round(gasoline_consumption, 2)


while True:
    orig = input("Starting Location: ")
    if orig == "quit" or orig == "q":
        break

    dest = input("Destination: ")
    if dest == "quit" or dest == "q":
        break

    url = main_api + urllib.parse.urlencode({"key": key, "from": orig, "to": dest})

    json_data = requests.get(url).json()

    print("URL: " + url)

    json_status = json_data["info"]["statuscode"]

    if json_status == 0:
        print("API Status: " + str(json_status) + " = A successful route call.\n")

        print("=============================================")
        print("Directions from " + orig + " to " + dest)
        print("Trip Duration:   " + json_data["route"]["formattedTime"])
        kilometers = round((json_data["route"]["distance"]) * 1.61, 2)
        print("kilometers:           " + str(kilometers))
        gasoline_consumption = calculate_gasoline_consumption(json_data["route"]["distance"])
        print("Gasoline Consumption: " + str(gasoline_consumption) + " liters")
        print("=============================================")

        for each in json_data["route"]["legs"][0]["maneuvers"]:
          print((each["narrative"]) + " (" + str("{:.2f}".format((each["distance"])*1.61) + " km)"))
        print("=============================================\n")